[versions]
kotlin = "2.2.10"

[libraries]
kotlin-logging = { group = "io.github.oshai", name = "kotlin-logging", version = "7.0.14" }

th2-common = { group = "com.exactpro.th2", name = "common", version = "5.17.2-dev" }

junit-bom = { group = "org.junit", name = "junit-bom", version = "5.14.3" }
mockito-kotlin = { group = "org.mockito.kotlin", name = "mockito-kotlin", version = "6.2.3" }
kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version = "1.10.2" }

[plugins]
th2-publish = { id = "com.exactpro.th2.gradle.publish", version = "0.3.14" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }